Repository frc2357/FRC-2022, pull requests merged in 2022-03, with the labels that each got.

#18 Modify Falcon subsystem and add example Trajectory code
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/RobotContainer.java
  robotbase/src/main/java/com/team2357/frc2022/commands/RecordPathCommand.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
  robotbase/src/main/java/com/team2357/frc2022/util/Utility.java
  robotbase/src/main/java/com/team2357/lib/controllers/InvertDriveControls.java
  robotbase/src/main/java/com/team2357/lib/subsystems/drive/FalconTrajectoryDriveSubsystem.java
  robotbase/src/main/java/com/team2357/lib/subsystems/drive/SkidSteerDriveSubsystem.java
  robotbase/src/main/java/com/team2357/lib/util/Utility.java
Labels: Needs Review

#24 Update pneumatics
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/RobotContainer.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
Labels: Needs Review

#27 Make Constant Subsystem Configuration
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/RobotContainer.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/FeederSubsystem.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
  robotbase/src/main/java/com/team2357/lib/controllers/InvertDriveControls.java
  robotbase/src/main/java/com/team2357/lib/util/Utility.java
Labels: Needs Review

#26 Update wpilib to 2022.4.1
  robotbase/build.gradle
Labels: Needs Review

#28 Add/kicker
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/RobotContainer.java
  robotbase/src/main/java/com/team2357/frc2022/commands/KickerSetSpeedCommand.java
  robotbase/src/main/java/com/team2357/frc2022/controls/GunnerControls.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/KickerSubsystem.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
  robotbase/vendordeps/RevLib.json
Labels: Needs Review

#9 Add shooter subsystem
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/RobotContainer.java
  robotbase/src/main/java/com/team2357/frc2022/commands/ShooterSetRPMsCommand.java
  robotbase/src/main/java/com/team2357/frc2022/controls/GunnerControls.java
  robotbase/src/main/java/com/team2357/frc2022/controls/IntakeDriveControls.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/ShooterSubsystem.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/util/VisionTargetSupplier.java
  robotbase/src/main/java/com/team2357/lib/util/RobotMath.java
Labels: Needs Review

#31 Fix arduino killing robot code
  robotbase/src/main/java/com/team2357/lib/arduino/ArduinoUSBController.java
Labels: bug, Needs Review

#36 Change CAN IDs to be what I want.
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
Labels: Needs Review

#39 Add/simple climber
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/RobotContainer.java
  robotbase/src/main/java/com/team2357/frc2022/commands/ClimberSetPivotCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/ClimberSimpleRunMotorsCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/ClimberToggleLatchCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/ClimberTogglePivotCommand.java
  robotbase/src/main/java/com/team2357/frc2022/controls/GunnerControls.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/ClimberSubsystem.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
  robotbase/vendordeps/REVLib.json
Labels: Needs Review

#38 Update feeder and add controls for it
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/RobotContainer.java
  robotbase/src/main/java/com/team2357/frc2022/controls/GunnerControls.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/FeederSubsystem.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
Labels: Needs Review

#46 Add climber smart motion
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/controls/GunnerControls.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/ClimberSubsystem.java
Labels: Needs Review

#47 Add shooter motor configuration
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/controls/GunnerControls.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/ShooterSubsystem.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
Labels: Needs Review

#51 Add sensor subsystem
  robotbase/src/main/java/com/team2357/frc2022/RobotContainer.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SensorSubsystem.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
Labels: Needs Review

#56 Update controls for gunner and driver
  robotbase/src/main/java/com/team2357/frc2022/RobotContainer.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/ClimbProgressionCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/FireCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/IntakeDeployToggleCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/TargetLockCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/TurretAxisCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/ClimberArmsCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/ClimberLatchCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/ClimberWinchAxisCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/FeederRollerAxisCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/IntakeArmsCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/IntakeRollerAxisCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/ShooterRollerAxisCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/intake/IntakeDeployCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/intake/IntakeStowCommand.java
  robotbase/src/main/java/com/team2357/frc2022/controls/AxisInterface.java
  robotbase/src/main/java/com/team2357/frc2022/controls/GunnerControls.java
  robotbase/src/main/java/com/team2357/frc2022/controls/IntakeDriveControls.java
  robotbase/src/main/java/com/team2357/lib/commands/InvertDriveCommand.java
  robotbase/src/main/java/com/team2357/lib/controllers/InvertDriveControls.java
Labels: Needs Review

#57 Fix PH CAN ID misassignment
  robotbase/src/main/java/com/team2357/frc2022/RobotContainer.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
Labels: Needs Review

#58 Update panic commands and triggers to work together.
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/TurretAxisCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/ClimberWinchAxisCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/FeederRollerAxisCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/IntakeRollerAxisCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/ShooterRollerAxisCommand.java
  robotbase/src/main/java/com/team2357/frc2022/controls/GunnerControls.java
Labels: Needs Review

#62 Add turret axis control
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/TurretAxisCommand.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/TurretSubsystem.java
Labels: Needs Review

#61 Add panic joystick control for intake
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/IntakeRollerAxisCommand.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/IntakeRollerSubsystem.java
Labels: Needs Review

#60 Add feeder axis control
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/RobotContainer.java
  robotbase/src/main/java/com/team2357/frc2022/commands/FeederSetSpeedCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/FeederRollerAxisCommand.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/FeederSubsystem.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
Labels: Needs Review

#59 Add setClimberAxisSpeed
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/commands/ClimberGoToRotationsCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/ClimberSimpleRunMotorsCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/ClimberWinchAxisCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/ClimberWinchResetCommand.java
  robotbase/src/main/java/com/team2357/frc2022/controls/GunnerControls.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/ClimberSubsystem.java
Labels: Needs Review

#69 Add shooter axis control
  robotbase/TODO.md
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/ShooterRollerAxisCommand.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/ShooterSubsystem.java
Labels: Needs Review

#66 Make the drive subsystems singletons.
  robotbase/src/main/java/com/team2357/lib/subsystems/drive/FalconTrajectoryDriveSubsystem.java
  robotbase/src/main/java/com/team2357/lib/subsystems/drive/SingleSpeedFalconDriveSubsystem.java
  robotbase/src/main/java/com/team2357/lib/subsystems/drive/SingleSpeedTalonDriveSubsystem.java
  robotbase/src/main/java/com/team2357/lib/subsystems/drive/TalonTrajectoryDriveSubsystem.java
Labels: Needs Review

#63 Add basic velocity PID for falcons
  robotbase/.SysId/sysid.json
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/RobotContainer.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
  robotbase/src/main/java/com/team2357/lib/commands/DriveVelocityCommand.java
  robotbase/src/main/java/com/team2357/lib/subsystems/drive/FalconTrajectoryDriveSubsystem.java
  robotbase/src/main/java/com/team2357/lib/subsystems/drive/SkidSteerDriveSubsystem.java
  robotbase/src/main/java/com/team2357/lib/util/Utility.java
Labels: Needs Review

#65 WIP: Add target lock functionality
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/Robot.java
  robotbase/src/main/java/com/team2357/frc2022/commands/TurretRotateCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/TargetLockCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/ClimberWinchResetCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/TurretResetCommand.java
  robotbase/src/main/java/com/team2357/frc2022/controls/GunnerControls.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/ShooterSubsystem.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/TurretSubsystem.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/util/VisionTargetSupplier.java
  robotbase/src/main/java/com/team2357/lib/commands/InvertDriveCommand.java
  robotbase/src/main/java/com/team2357/lib/commands/LimelightHumanPipelineCommand.java
  robotbase/src/main/java/com/team2357/lib/commands/LimelightTargetingPipelineCommand.java
  robotbase/src/main/java/com/team2357/lib/commands/VisionChangePipelineCommand.java
  robotbase/src/main/java/com/team2357/lib/subsystems/LimelightSubsystem.java
  robotbase/src/main/java/com/team2357/lib/subsystems/TogglableLimelightSubsystem.java
Labels: Needs Review

#73 Change/intake to srx
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/IntakeDeployToggleCommand.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/FeederSubsystem.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/IntakeRollerSubsystem.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SensorSubsystem.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
  robotbase/src/main/java/com/team2357/lib/subsystems/drive/FalconTrajectoryDriveSubsystem.java
Labels: Needs Review

#30 Create trajectory pathing utilities
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/RobotContainer.java
  robotbase/src/main/java/com/team2357/frc2022/commands/RecordPathCommand.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
  robotbase/src/main/java/com/team2357/frc2022/util/AvailableTrajectories.java
  robotbase/src/main/java/com/team2357/frc2022/util/TrajectoryUtil.java
  robotbase/src/main/java/com/team2357/lib/controllers/InvertDriveControls.java
  robotbase/src/main/java/com/team2357/lib/subsystems/drive/FalconTrajectoryDriveSubsystem.java
Labels: In Progress

#71 Add/shooter vision
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/commands/feeder/FeederAdvanceCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/feeder/FeederToShooterCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/FireLowHubCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/FireLowHubCommandGroup.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/FireTaxiLineCommandGroup.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/FireVisionCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/human/panic/ShooterRollerAxisCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/shooter/ShootLowHubCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/shooter/ShootTaxiLineCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/shooter/ShooterSetRPMsCommand.java
  robotbase/src/main/java/com/team2357/frc2022/controls/GunnerControls.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/ShooterSubsystem.java
  robotbase/src/main/java/com/team2357/lib/subsystems/LimelightSubsystem.java
Labels: In Progress

#81 A turret limits
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/TurretSubsystem.java
Labels: Needs Review

#80 Add second intake motor
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/RobotContainer.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/IntakeRollerSubsystem.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
Labels: Needs Review

#82 Fix turret limits
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
Labels: Needs Review

#84 Modify intake deploy to take one or two cargo
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/RobotContainer.java
  robotbase/src/main/java/com/team2357/frc2022/commands/intake/IntakeDeployCommand.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SensorSubsystem.java
  robotbase/src/main/java/com/team2357/lib/subsystems/drive/FalconTrajectoryDriveSubsystem.java
Labels: Needs Review

#89 Fix falcon drive subsystem
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/Robot.java
  robotbase/src/main/java/com/team2357/frc2022/RobotContainer.java
  robotbase/src/main/java/com/team2357/frc2022/commands/RecordPathCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/auto/AutoDriveCommand.java
  robotbase/src/main/java/com/team2357/frc2022/commands/auto/TwoBallAutoCommand.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
  robotbase/src/main/java/com/team2357/frc2022/util/AvailableTrajectories.java
  robotbase/src/main/java/com/team2357/frc2022/util/TrajectoryUtil.java
  robotbase/src/main/java/com/team2357/lib/commands/DriveVelocityCommand.java
  robotbase/src/main/java/com/team2357/lib/subsystems/drive/FalconDriveSubsystem.java
  robotbase/src/main/java/com/team2357/lib/subsystems/drive/SingleSpeedFalconDriveSubsystem.java
  robotbase/src/main/java/com/team2357/lib/util/Utility.java
Labels: Needs Review

#91 Add internal encoders
  robotbase/src/main/java/com/team2357/frc2022/Constants.java
  robotbase/src/main/java/com/team2357/frc2022/RobotContainer.java
  robotbase/src/main/java/com/team2357/frc2022/subsystems/SubsystemFactory.java
  robotbase/src/main/java/com/team2357/frc2022/util/AvailableTrajectories.java
  robotbase/src/main/java/com/team2357/lib/subsystems/drive/FalconDriveSubsystem.java
Labels: Needs Review
